INSERT INTO furniture_entity (id, name) VALUES (1, 'Dining Table');
INSERT INTO furniture_entity (id, name) VALUES (2, 'Office Chair');
INSERT INTO furniture_entity (id, name) VALUES (3, 'Sofa');
INSERT INTO furniture_entity (id, name) VALUES (4, 'Coffee Table');
INSERT INTO furniture_entity (id, name) VALUES (5, 'Bed Frame');
INSERT INTO furniture_entity (id, name) VALUES (6, 'Bookshelf');
INSERT INTO furniture_entity (id, name) VALUES (7, 'Wardrobe');
INSERT INTO furniture_entity (id, name) VALUES (8, 'Nightstand');
INSERT INTO furniture_entity (id, name) VALUES (9, 'Dresser');
INSERT INTO furniture_entity (id, name) VALUES (10, 'TV Stand');
INSERT INTO furniture_entity (id, name) VALUES (11, 'Kitchen Cabinet');
INSERT INTO furniture_entity (id, name) VALUES (12, 'Bar Stool');
INSERT INTO furniture_entity (id, name) VALUES (13, 'Console Table');
INSERT INTO furniture_entity (id, name) VALUES (14, 'Sideboard');
INSERT INTO furniture_entity (id, name) VALUES (15, 'Desk');
INSERT INTO furniture_entity (id, name) VALUES (16, 'Recliner Chair');
INSERT INTO furniture_entity (id, name) VALUES (17, 'Folding Chair');
INSERT INTO furniture_entity (id, name) VALUES (18, 'Bench');
INSERT INTO furniture_entity (id, name) VALUES (19, 'Storage Ottoman');
INSERT INTO furniture_entity (id, name) VALUES (20, 'Patio Chair');
INSERT INTO furniture_entity (id, name) VALUES (21, 'Dining Bench');
INSERT INTO furniture_entity (id, name) VALUES (22, 'Vanity Table');
INSERT INTO furniture_entity (id, name) VALUES (23, 'Chaise Lounge');